export const BankingData = [
    {
        title: "Banking That Works for Your Business",
        para: "<p>Experience seamless digital banking with Montra designed to simplify transactions, manage cash flow, and unlock access to credit and financial tools. Whether you're a small shop or a scaling enterprise, Montra helps you bank smarter, not harder.</p>",
        link: "/business/banking",
        color: "#FF8100",
        icon: "/assets/images/business/banking-icon.svg",
        field: "Banking",
    },
    {
        title: "Accept Payments without Limits",
        para: "<p>Your Montra Business Account unlocks everything you need to get paid, faster and easier.</p><ol class='pl-[2vw] list-decimal space-y-[0.5vw]'><li>Accept payments via QR Scan, Bank Transfers, Tap and Pay, or POS.</li><li>Easily create and send professional invoices to collect payments.</li><li>Share instant Payment Links and watch funds flow in, hassle-free.</li></ol><p>From customer checkout to cash flow, Montra keeps your business moving forward.</p>",
        link: "/business/payments",
        color: "#215CFF",
        icon: "/assets/images/business/payments-icon.svg",
        field: "Payments",
    },
    {
        title: "Earn More as a Montra Agent",
        para: "<p>Bring banking closer, Start offering essential Agency Banking services right in your community</p><p>Register through Montra Business to become an Agent or simply add an Agent account if you’re already a registered Montra Merchant.</p>",
        link: "/business/agency-banking",
        color: "#35C771",
        icon: "/assets/images/business/agency-banking-icon.svg",
        field: "Agency Banking",
    },
    {
        title: "Smarter Inventory. Efficient Business.",
        para: "<p>With your Montra Business Account, you can seamlessly purchase from other businesses, pay directly through invoices, send your own invoices to get paid instantly, and place orders with linked distributors, all in one streamlined system. Simplify operations, stay stocked, and keep your business moving forward with Montra.</p>",
        link: "/business/inventory-management",
        color: "#111111",
        icon: "/assets/images/business/inventory-icon.svg",
        field: "Inventory Management",
    },
    {
        title: "Sell Online  For Free",
        para: "<p>Dream bigger, sell smarter. With Montra, you don’t need a website to reach more customers and grow your business.</p><p>List your products, share your unique store link, and get paid instantly,  all from your phone, with zero setup cost.</p><p>Your shop. Your terms. Your future.</p>",
        link: "/business/montra-store",
        color: "#FB2F55",
        icon: "/assets/images/business/montra-store-icon.svg",
        field: "Montra Store",
    },
    {
        title: "One Gateway, Multiple Payments Methods",
        para: "<p>Seamless Payments. Everywhere.Integrate the Montra Payment Gateway into your website or mobile app and let your customers pay their way: </p><ul class='pl-[2vw] space-y-[0.5vw] list-disc'><li>Debit & Credit Cards</li><li>Bank Accounts via QR Scan</li><li>Montra App; with account balance or Installments</li><li>USSD for offline payments</li></ul><p>Fast integration, secure transactions, and more ways to get paid.</p>",
        link: "/business/payment-gateway",
        color: "#7A78FF",
        icon: "/assets/images/business/payment-gateway-icon.svg",
        field: "Payment Gateway",
    },
    {
        title: "Accept Contactless Payments, No Extra Terminals",
        para: "<p>With Montra’s Tap to Pay, your customers can accept in-person, contactless payments directly on NFC-enabled Android devices  using only the Montra App. No extra terminals, no hardware, just tap and go. Accept payments from any physical card and keep your business moving effortlessly.</p>",
        link: "/business/tap-and-pay",
        color: "#FFB909",
        icon: "/assets/images/business/tap-and-pay-icon.svg",
        field: "Tap & Pay",
    },
];